---
  - hosts: router
    gather_facts: yes
    connection: local

    tasks:
        - name: Enable Netconf
          junos_netconf:
              state: present

        - name: Create user account
          junos_user:
             aggregate:
             - {name: ben.villatore, role: super-user, state: present, encrypted_password: xxxxxxxxxxxx}
             - {name: pravin.rathod, role: super-user, state: present, encrypted_password: xxxxxxxxxxxx.}
             - {name: santanu.mandal, role: super-user, state: present, encrypted_password: xxxxxxxxxxxx}
             - {name: tejas.mokashi, role: super-user, state: present, encrypted_password: xxxxxxxxxxxx}

        - name: Disable Netconf
          junos_netconf:
              state: absent
...


ansible-playbook -vvvvv -i devices show_commands.yml -u tejas.mokashi -k
